<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fb_info</name>
   <tag></tag>
   <elementGuidId>944d6820-4dd3-4543-8c87-86e91d1c14b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[href=&quot;https://facebook.com/rubicainc&quot;]</value>
   </webElementProperties>
</WebElementEntity>
